language: python
python:
- '2.7'
- '3.5'
- '3.6'
script:
- PYTHONPATH=`pwd` pytest -s ./tests
deploy:
  provider: pypi
  user: lensonp
  password: 
    secure: DvizT02QRHPNh5tDnF4mmkc93YS9br/nXIfoXqgdh8SSvhKQ/r/vijt1BQo/00g2/y8rbN7nb8riIafSXgAc6JkogvN/cLcGpZQ7hidGRbChZvszbDp6rTuJKdx53XnrthClyQIl4iOqNYyW8BsCZI2i5Gf0mn1KzuVS9yz4DgsrRLIv4IuExNWhQ/O+5exWMZyomKkxjU6L5Aij5ebOxQeIlvx3zFjv+v7TFwYB2mLyIiRVX3Kqz2S2fRl0x4DJEH4OalQcMBLRAtIK+RG0GA9WImOP7V/cSb8/h1SH78UDeClpy9Tz91CxAeZ9diljSm1Y00ANWhGgG8lAe9GPV6iwnU2rpzkLjh2ZWXWo1WBcVusn13BfhJd8UN2SWTEx6/KBb3QcF2YoJuyzS++T1XaQEgao20wMI1FL4pOSk4qDNKT4Vfhl+KjOkF8FokJi2uRnVtiTicihl81IMLtnW4H0ht/Mz03RKth6gapxxIVJZUuSb1yME6lRJgEUt1aNXqO930Z9mNcfyxGHYAdS3SsLztRA2iU399kQo8X5PxrGK9tcUEPeoKz8vO+MSDYkAxSR+O12OGByZ8/8bQpybrsIRv1AkwaaH0GcZbgK8ApIG54W0B57IIrulicOjielxR5pA+PnronL/GkNWafZfTq1Ezb+W/TEpm9Z5agsfy4=
  on:
    distributions: sdist bdist_wheel
    branch: master
