language: python
python:
- '2.7'
- '3.5'
- '3.6'
script:
- PYTHONPATH=`pwd` pytest -s ./tests
deploy:
  provider: pypi
  user: lensonp
  password: 
    secure: "UmXPBi+IteoCuLNyN9mxTZcpZ/lzMc3swum5syX76F0/EX8Ews8QKG5AfzEfQ0GXbHLhcvkDSTFe/K2hZMAlYGwTBWLamvBHR6TotyG052rN9xAOYR/0sGkVHeQiaDvGtHLBTyXkCvao1XHPsdRqf5VxevvH5/8sf9605RgBr0wMvaFOiWhqd7ugu8jPCV64Cm69kPRlr/sfBD2PB4og17yptfhl/qhCcXczEPRvVZxQasO/b1VCv45nNIKZ9AjWahrXul1elm5VIdeNb3p3poLatlQtZgaOqC7NxQM6tTZ361Y6MzU3yPrKhBF/NpF1Eo5h4koM1HRXhS9bqOUHPUwYCIQE7nI/+QV9+6SzRi/DfxjHTnnVkrZ7lsGPna/Nx8Q6+7wtWZ5f42SNE4puLh5Y/4ELfhYGNvuuLlL5PqPkJ4LSmTF9U+GIiUzfTUtTq7lHzd59iyE9x35R1hvCDa3khlerKS31w0Ptvhuh4sH+NhwkXTNVTpcLkJFNDh52U7EmxLdxauPvFqQKTgImN2OxVoNtVXsEz4XKQoXrm+ecm0cOOqDwoj9MOG0L6qYKaNvf0zcNNWjJb/HY6RVCWtvRVri9Kd8bmit+mB0892R6zI+Ahtq8jgohH5fOoISP+0rg/8VPH+X9tGXxwD+zn/WX9NIC1HpKStuf+x6sNkI="
  on:
    distributions: sdist bdist_wheel
    branch: master
